#!/bin/sh
if [ $(nvram get upnp_enabled) = "1" ]; then
	echo "miniupnpd starting ..."
	iptables_flush.sh 2>&- >&-
	killall miniupnpd 2>&-
	iptables_removeall.sh 2>&- >&-
	iptables_init.sh
	miniupnpd -i $(nvram get wan_ifname) -a $(nvram get lan_ipaddr) -p 5000 -U &
else
	echo "miniupnpd service is disabled. Set nvram upnp_enabled to '1' to enable."
fi
