#!/bin/sh
. /etc/functions.sh
. /lib/config/uci.sh
uci_load "upnpd"
if [ "$CONFIG_general_enable" = "1" ]; then
	echo "miniupnpd starting ..."
	iptables_flush.sh 2>&- >&-
	killall miniupnpd 2>&-
	iptables_init.sh 2>&- >&-
	# get bitspeed information, if provided
	upnpd_up_bitspeed=$CONFIG_general_up_bitspeed
	upnpd_down_bitspeed=$CONFIG_general_down_bitspeed
	bitspeed_str=""
	[ -n "$upnpd_up_bitspeed" ] && [ -n "$upnpd_down_bitspeed" ] && {
		# covert to bytespeed
		let upnpd_up_bytespeed=$upnpd_up_bitspeed*1024/8
		let upnpd_down_bytespeed=$upnpd_down_bitspeed*1024/8
		bitspeed_str="-B $upnpd_down_bytespeed $upnpd_up_bytespeed"
	}	
	if [ "$CONFIG_general_log_output" = "1" ]; then
		miniupnpd -i $(nvram get wan_ifname) -a $(nvram get lan_ipaddr) -p 5000 -U $bitspeed_str | logger -t miniupnpd &
	else
		miniupnpd -i $(nvram get wan_ifname) -a $(nvram get lan_ipaddr) -p 5000 -U $bitspeed_str
	fi
else
	echo "To enable miniupnpd set option enable = '1' in /etc/config/upnpd."
fi
