#!/bin/sh
# don't run the telnetd if dropbear (ssh) is active since
# OpenWrt will have disabled the telnetd login anyway.
[ ! -f "/etc/dropbear/dropbear_rsa_host_key" ] && {
	telnetd -l /bin/login
}
