#!/bin/sh

#
# replaced at build time with revision number
#
this_revision=__SVN_REVISION__
last_cleaned=$(nvram get webif_rev)
if [ "$this_revision" = "$last_cleaned" ]; then
	exit 0
fi

#
# remove old wan.sh and lan.sh (now is wan-lan.sh)
#
# to support squashfs filesystems with symlink hack, we can't just
# delete this, they must exist in some form else they return from the 
# RO filesystem. So, we'll symlink them to nowhere.
#

# merged into wan-lan.sh
if [ -f /rom/www/cgi-bin/webif/wan.sh ]; then
	echo "" > "/www/cgi-bin/webif/wan.sh" 	  
else
	rm "/www/cgi-bin/webif/wan.sh"
fi

# merged into wan-lan.sh
if [ -f /rom/www/cgi-bin/webif/lan.sh ]; then
	echo "" > "/www/cgi-bin/webif/lan.sh" 	 
else
	rm "/www/cgi-bin/webif/lan.sh"
fi

# old name for like 2 builds
if [ -f /rom/www/cgi-bin/webif/wan_lan.sh ]; then
	echo "" > "/www/cgi-bin/webif/wan_lan.sh" 	 
else
	rm "/www/cgi-bin/webif/wan_lan.sh"
fi

# old name for like 2 builds
if [ -f /rom/www/cgi-bin/webif/hardwarestats.sh ]; then
	echo "" > "/www/cgi-bin/webif/hardwarestats.sh" 	 
else
	rm "/www/cgi-bin/webif/hardwarestats.sh"
fi

#
# early alpha versions of the x-wrt webif qos-config.sh would create a 'dummy'
# /etc/qos.conf if Rudy's QoS scripts weren't installed.
#
# if qos.conf exists and qos-re package not installed, delete
#
if [ -f "/etc/qos.conf" ]; then
	ipkg list_installed | grep qos-re 2>&1 > /dev/null
	if [ $? != 0 ]; then
 		echo " $0: cleaning up unused /etc/qos.conf"
		echo "" > "/etc/qos.conf"
	fi	
fi

#
# I really hate to do this, but seems have to..
#
nvram set "webif_rev=$this_revision"
nvram commit
