#!/bin/sh
# configure opendns nameservers if enabled
. /lib/config/uci.sh
. /usr/lib/webif/functions.sh

start() {
	uci_load "webif"
	[ "$CONFIG_misc_opendns" = "1" ] && {
		! grep -q "208.67.222.222" "/tmp/resolv.conf" && {
			echo "Setting OpenDNS nameservers ..."
			local _ltemp
			_ltemp=$(mktemp "/tmp/.newresolv-XXXXXX")
			mv -f "/tmp/resolv.conf" "$_ltemp"
			echo "nameserver 208.67.222.222" > /tmp/resolv.conf
			echo "nameserver 208.67.220.220" >> /tmp/resolv.conf
			cat "$_ltemp" >> "/tmp/resolv.conf"
			rm -f "$_ltemp"			
		}
	}
}

stop() {
	remove_lines_from_file "/tmp/resolv.conf" "208.67.222.222"
	remove_lines_from_file "/tmp/resolv.conf" "208.67.220.220"
}

restart() {
	stop
	start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        restart
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?