#!/bin/sh
# configure opendns nameservers if use_opendns is set
use_opendns=$(nvram get "use_opendns")
[ "$use_opendns" = "1" ] && {
	! grep "208.67.222.222" "/tmp/resolv.conf" && {
		echo "Setting OpenDNS nameservers ..."
		local _ltemp
		_ltemp=$(mktemp "/tmp/.newresolv-XXXXXX")
		mv -f "/tmp/resolv.conf" "$_ltemp"
		echo "nameserver 208.67.222.222" > /tmp/resolv.conf
		echo "nameserver 208.67.220.202" >> /tmp/resolv.conf
		cat "$_ltemp" >> "/tmp/resolv.conf"
		rm -f "$_ltemp"
	}
}
