#!/bin/sh

case "$(nvram get openvpn_cli)" in
	on|enabled|1)
		continue
	;;
	off|disabled|0)
		exit 0
	;;
esac

case "$1" in
	start)
		SERVER=$(nvram get openvpn_cli_server)
		PROTO=$(nvram get openvpn_cli_proto)
		PORT=$(nvram get openvpn_cli_port)

		[ "$SERVER" ] && {
			SERVER_OPTION="--remote $SERVER --nobind"
		}
		case "$(nvram get openvpn_cli_auth)" in
			cert)
				AUTH_OPTION="--client --pkcs12 /etc/openvpn/certificate.p12"
			;;
			psk)
				AUTH_OPTION="--secret /etc/openvpn/shared.key"
			;;
			pem)
				AUTH_OPTION="--client --ca /etc/openvpn/ca.crt --cert /etc/openvpn/client.crt --key /etc/openvpn/client.key"
			*)
				logger "$0: unknown authentication type, aborting!"
				exit
			;;
		esac
		[ -f "$AUTH_FILE" ] || {
			logger "$0: no certificat/keyfile found!"
			exit
		}
		openvpn --proto  "${PROTO:-udp}"		\
			--port   "${PORT:-1194}"		\
			$SERVER_OPTION				\
			--dev tun				\
			$AUTH_OPTION				\
			--comp-lzo				\
			--daemon				\
			--status /tmp/openvpn-status.log	\
			--verb 3
	;;
	restart)
		$0 stop
		sleep 3
		$0 start
	;;
	reload)
		killall -SIGHUP openvpn
	;;
	stop)
		killall openvpn
	;;
esac
