#!/bin/sh
# This file is NOT synchronized between branches.
#
# identification of the device
#
START=90
. /lib/config/uci.sh
uci_load "webif"
device_name="$CONFIG_general_device_name"

[ -z "$device_name" ] && [ -f "/proc/diag/model" ] && device_name=$(cat "/proc/diag/model")
while [ -z "$device_name" ]; do  
        dd bs=1024 skip=212 count=16 if=/dev/mtd/0 2>/dev/null | strings | grep -q W54G
        [ $? = "0" ] && {
               device_name="Linksys WRT54G"
               break
        }
        dd bs=1024 count=1 skip=5 if=/dev/mtd/0 2>/dev/null | strings | grep "WL500gp"
        [ $? = "0" ] && {
               device_name="ASUS WL-500gp"
               break
        }
break
done
[ "$device_name" != "$CONFIG_general_device_name" ] && {
	echo "Device: $device_name" 	
	echo "Committing new device id ..."		
	uci_set "webif" "general" "device_name" "$device_name"
	uci_commit "webif"
}
