#!/bin/sh
# This file is compatible with White Russian and Kamikaze.
old_firmware_name=$(uci get webif.general.firmware_name)
old_firmware_subtitle=$(uci get webif.general.firmware_subtitle)
old_firmware_version=$(uci get webif.general.firmware_version)
firmware_name="$old_firmware_name"
firmware_subtitle="$old_firmware_subtitle"
firmware_version="$old_firmware_version"

[ -z "$old_firmware_name" ] && {
	if grep -qi "KAMIKAZE" "/etc/banner"; then
		firmware_name="OpenWrt Kamikaze"
	else	
		firmware_name="OpenWrt White Russian"		
	fi	
}

[ -z "$old_firmware_subtitle" ] && {
	firmware_subtitle="With X-Wrt Extensions"
}

if grep -q "RC5" "/etc/banner"; then
	firmware_version="RC5"	
elif grep -q "RC6" "/etc/banner"; then
	firmware_version="RC6"	
elif [ -f "/etc/openwrt_version" ]; then
	firmware_version=$(cat "/etc/openwrt_version")
else
	firmware_version="unknown"
fi

#
# if any variables changed, commit the change
#
if [ "$old_firmware_version" != "$firmware_version" ] ||
	[ "$old_firmware_name" != "$firmware_name" ] ||
	[ "$old_firmware_subtitle" != "$firmware_subtitle" ]; then
	uci set "webif.general.firmware_name=$firmware_name"
	uci set "webif.general.firmware_version=$firmware_version"
	uci set "webif.general.firmware_subtitle=$firmware_subtitle"
	uci commit
fi



