#!/bin/sh

dyndns() {
    # see http://wiki.openwrt.org/PublishYourWANIp
    LOGGING_TAG="dyndns-updater"
    ACCOUNT=$(nvram get ddns_username)
    PASS=$(nvram get ddns_password)
    DOMAIN=$(nvram get ddns_hostname)
    IFACE=$(nvram get wan_iface)

    if [ "$ACCOUNT" = "" -o "$PASS" = "" -o "$DOMAIN" = "" ]; then
	logger -t ${LOGGING_TAG} -- "DynDNS Updatescript $0 is not properly configured!"
	echo "The DynDNS Updatescript $0 is not properly configured!"
	echo "To configure, set the following nvram variables:"
	echo "ddns_username:  DynDNS Username"
	echo "ddns_password:  DynDNS Password"
	echo "ddns_hostname:  DynDNS Hostname"
	echo ""
	echo "Example:"
	echo "nvram set ddns_username JoeSchmuh"
	echo "nvram set ddns_password SomethingSecret"
	echo "nvram set ddns_hostname JoeSchmuh.is-a-geek.net"
	echo "nvram commit"
	exit 4
    fi
    
    wget -q http://checkip.dyndns.org/index.html --output-document=/etc/dyndns.org-ip.new

    if [ "`cat /etc/dyndns.org-ip`" = "`cat /etc/dyndns.org-ip.new`" ]
    then 
	echo "No new IP";
    else 
	rm -f /etc/dyndns.org-ip.dbg
	wget -q -O /etc/dyndns.org-ip.dbg "http://$ACCOUNT:$PASS@members.dyndns.org/nic/update?system=dyndns&hostname=$DOMAIN&wildcard=ON&offline=NO"
    
	if ! [ -f /etc/dyndns.org-ip.dbg ]; then
	    logger -t ${LOGGING_TAG} -- "Couldn't update ip-address for \"$ACCOUNT.dyndns.org\""
	    logger -t ${LOGGING_TAG} -- "wget failed to download the file!"
	    exit 2
	fi
	
	if [ "$(cat /tmp/dyndns.org-ip.dbg | awk '{printf("%s",$2);}')" != "${IP}" ]; then
	    logger -t ${LOGGING_TAG} -- "Error while updating ip-address:"
	    cat /tmp/dyndns.org-ip.dbg | logger -t ${LOGGING_TAG}
	    rm -f /tmp/dyndns.org-ip.dbg
	    exit 3
	fi
	
	rm -f /tmp/dyndns.org-ip.dbg
	
	wget -q http://checkip.dyndns.org/index.html --output-document=/etc/dyndns.org-ip
	
	logger -t ${LOGGING_TAG} -- "IP address successfully updated to ${IP}"    
    fi
}

case "$1" in
    start)
	dyndns
	;;
esac
