#!/bin/sh

case "$1" in
	start)
	case "$(uci get openvpn general mode)" in
		client)
			SERVER=$(uci get openvpn client ipaddr)
			PROTO=$(uci get openvpn general proto)
			PORT=$(uci get openvpn general port)
	
			[ "$SERVER" ] || {
				logger "$0: remote server not configured!"
				exit
			}
			case "$(uci get openvpn client auth)" in
				cert)
					AUTH_OPTION="--client --pkcs12"
					AUTH_FILE="/etc/openvpn/certificate.p12"
				;;
				psk)
					AUTH_OPTION="--secret"
					AUTH_FILE="/etc/openvpn/shared.key"
				;;
				*)
					logger "$0: unknown authentication type, aborting!"
					exit
				;;
			esac
			[ -f "$AUTH_FILE" ] || {
				logger "$0: no certificat/keyfile found!"
				exit
			}
			openvpn --proto  "${PROTO:-udp}"		\
				--port   "${PORT:-1194}"		\
				--remote "$SERVER"			\
				--dev tun				\
				--nobind				\
				$AUTH_OPTION "$AUTH_FILE"		\
				--comp-lzo				\
				--daemon				\
				--status /tmp/openvpn-status.log	\
				--verb 3
			server)
				echo "Not yet implimented"
				exit 0
			;;
			*)
				exit 0
		;;
	;;
	restart)
		$0 stop
		sleep 3
		$0 start
	;;
	reload)
		killall -SIGHUP openvpn
	;;
	stop)
		killall openvpn
	;;
esac
