#!/bin/sh
#
# Webif post-install script.
#
if [ "`grep "Mesh" "${IPKG_INSTROOT}/www/cgi-bin/webif/.categories"`" = "##WEBIF:category:Mesh" ]; then
	cat "${IPKG_INSTROOT}/www/cgi-bin/webif/.categories" |sed '/##WEBIF:category:Mesh/a\
##WEBIF:category:Applications'>"${IPKG_INSTROOT}/www/cgi-bin/webif/.categories"
else
	cat "${IPKG_INSTROOT}/www/cgi-bin/webif/.categories" |sed '/##WEBIF:category:Network/a\
##WEBIF:category:Applications'>"${IPKG_INSTROOT}/www/cgi-bin/webif/.categories"
fi
