#!/bin/sh
# configure opendns nameservers if enabled
. /usr/lib/webif/functions.sh

enable() {
	local opendns_enabled=$(nvram get opendns_enabled)
	[ "$opendns_enabled" = "1" ] && {
		! grep -q "208\.67\.222\.222" "/tmp/resolv.conf" 2>/dev/null || ! grep -q "208\.67\.220\.220" "/tmp/resolv.conf" 2>/dev/null && {
			local _ltemp
			_ltemp=$(mktemp "/tmp/.newresolv-XXXXXX")
			echo "nameserver 208.67.222.222" > "$_ltemp"
			echo "nameserver 208.67.220.220" >> "$_ltemp"
			grep -v "208\.67\.22\(2\.222\|0\.220\)" "/tmp/resolv.conf" >> "$_ltemp"
			cat "$_ltemp" > "/tmp/resolv.conf"
			rm -f "$_ltemp"
		}
	}
}

disable() {
	remove_lines_from_file "/tmp/resolv.conf" "208.67.222.222"
	remove_lines_from_file "/tmp/resolv.conf" "208.67.220.220"
}

case "$1" in
	enable|start)
		enable
		;;
	disable|stop)
		disable
		;;
	*)
		echo $"Usage: $0 {enable|disable}"
		exit 1
esac

exit $?
