#!/bin/sh
# configure opendns nameservers if enabled
. /etc/functions.sh
. /lib/config/uci.sh
. /usr/lib/webif/functions.sh

start() {
	uci_load "webif"
	[ "$CONFIG_misc_opendns" = "1" ] && {
		! grep -q "208\.67\.222\.222" "/tmp/resolv.conf" || ! grep -q "208\.67\.220\.220" "/tmp/resolv.conf" && {
			echo "Setting OpenDNS nameservers ..."
			local _ltemp
			_ltemp=$(mktemp "/tmp/.newresolv-XXXXXX")
			echo "nameserver 208.67.222.222" > "$_ltemp"
			echo "nameserver 208.67.220.220" >> "$_ltemp"
			grep -v "208\.67\.22\(2\.222\|0\.220\)" "/tmp/resolv.conf" >> "$_ltemp"
			cat "$_ltemp" > "/tmp/resolv.conf"
			rm -f "$_ltemp"			
		}
	}
}

stop() {
	remove_lines_from_file "/tmp/resolv.conf" "208.67.222.222"
	remove_lines_from_file "/tmp/resolv.conf" "208.67.220.220"
}

restart() {
	stop
	start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        restart
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?