#!/bin/sh
# invoke ntp server based on nvrams vars ntp_server and time_zone
if [ -f "/usr/sbin/ntpclient" ] || \
	[ -f "/usr/bin/ntpclient" ] || \
	[ -f "/sbin/ntpclient" ] || \
	[ -f "/bin/ntpclient" ]; then

	# get server, use pool.ntp.org if not set
	NTP_SERVER=$(nvram get ntp_server)
	if [ -z "$NTP_SERVER" ]; then
		NTP_SERVER="0.openwrt.pool.ntp.org"
		nvram set "ntp_server=$NTP_SERVER"
	fi

	# launch ntpclient
	killall ntpclient
	ntpclient -i 86400 -h $NTP_SERVER &
else
	logger "$0: ntpclient not found to be installed."
fi
