#!/bin/sh
#syslogd options
# -m MIN          Minutes between MARK lines (default=20, 0=off)
# -n              Run as a foreground process
# -O FILE         Use an alternate log file (default=/var/log/messages)
# -S              Make logging output smaller.
# -s SIZE         Max size (KB) before rotate (default=200KB, 0=off)
# -b NUM          Number of rotated logs to keep (default=1, max=99, 0=purge)
# -R HOST[:PORT]  Log to IP or hostname on PORT (default PORT=514/UDP)
# -L              Log locally and via network logging (default is network only)
# -C [size(KiB)]  Log to a circular buffer (read the buffer using logread)

DEFAULT_MARK=0
DEFAULT_SIZE=16
DEFAULT_TYPE="circular"
DEFAULT_IP=""
DEFAULT_PORT="514"

# retrieve nvram values
syslog_ip=$(nvram get log_ipaddr)
syslog_port=$(nvram get log_port)
syslog_size=$(nvram get log_size)
syslog_type=$(nvram get log_type)
syslog_mark=$(nvram get log_mark)

# verify values
[ $syslog_type = "circular" ] 2>>/dev/null || [ $syslog_type = "file" ] 2>>/dev/null || syslog_type=$DEFAULT_TYPE
[ $syslog_size -gt 0 ] 2>>/dev/null || syslog_size=$DEFAULT_SIZE
eval $(ipcalc "$syslog_ip")
[ $syslog_ip = "$IP" ] 2>>/dev/null || syslog_ip=$DEFAULT_IP
[ -z $syslog_port] 2>>/dev/null || [ $syslog_port -lt 0 ] 2>>/dev/null || [ $syslog_port -gt 65535 ] 2>>/dev/null && syslog_port=$DEFAULT_PORT 
[ $syslog_mark -gt 0 ] 2>>/dev/null || syslog_mark=$DEFAULT_MARK

# build command syslog command line
if [ "$syslog_type" = "circular" ] ; then
	SYSLOG_CMD="-C $syslog_size -m $syslog_mark ${syslog_ip:+-L -R $syslog_ip:$syslog_port}"
else	SYSLOG_CMD="-s $syslog_size -m $syslog_mark ${syslog_ip:+-L -R $syslog_ip:$syslog_port}"
fi

# start syslogd
/sbin/syslogd $SYSLOG_CMD