#!/usr/bin/lua
--------------------------------------------------------------------------------
-- freeradius apply handler
-- Author(s) [in order of work date]:
--       Fabián Omar Franzotti
--         
-- Configuration files referenced:
--    freeradius-check
--    freeradius-reply
--
--------------------------------------------------------------------------------
print ("Committing freeradius_check...<br>")
os.execute("uci commit freeradius_check")
os.execute("rm /tmp/.uci/freeradius_check > /dev/null 2>&1")
print ("Committing freeradius_reply...<br>")
os.execute("uci commit freeradius_reply")
os.execute("rm /tmp/.uci/freeradius_reply > /dev/null 2>&1")

local freeradius = uciClass.new("freeradius")
if tonumber(freeradius.webadmin.userlevel) < 4 then
  print ("Writing users...<br>")
-- Process users
  local user_str = ""
  local sep = ""
  local users_chk = uciClass.new("freeradius_check")
  local users_rpl = uciClass.new("freeradius_reply")
  for i=1 ,#users_chk.sections do
    local name = users_chk.sections[i].name
    if name ~= "default" then
      local checks = users_chk[name]
      local replys = users_rpl[name]
      user_str = user_str .. "\n\n"..name
      sep = "\t"
      for j, k in pairs(checks) do
        if type(k) ~= "table" then
          if string.trim(j) == "User_Password" then
            user_str = user_str..sep.. string.gsub(j,"_","-").." := \""..k.."\""
          else
            user_str = user_str..sep.. string.gsub(j,"_","-").." := "..k
          end
          sep = ", "
        end
      end    
      sep = "\n\t"
      for j, k in pairs(replys) do
        if type(k) ~= "table" then
          user_str = user_str..sep.. string.gsub(j,"_","-").." = "..k
          sep = ", "
        end
      end
    end
  end
  sep = ""
  user_str = user_str.."\n\nDEFAULT\t"
  for i, v in pairs (users_chk.default) do
    if type(v) ~= "table" then
      user_str = user_str..sep..string.gsub(i,"_","-").." := "..v
      sep = ", "
    end
  end
  sep = "\n\t"
  for i, v in pairs (users_rpl.default) do
    if type(v) ~= "table" then
      user_str = user_str..sep..string.gsub(i,"_","-").." = "..v
      sep = ",\n\t"
    end
  end
  local pepe = io.open("/etc/freeradius/users","w")
  pepe:write(user_str)
  pepe:close()
end
__RESTART["radiusd"] = {}
__RESTART["radiusd"]["pkg"] = "freeradius"
__RESTART["radiusd"]["cfg"] = "webadmin"
__RESTART["radiusd"]["opt"] = "enable"
__RESTART["radiusd"]["init"] = "/etc/init.d/radiusd"
