#!/usr/bin/lua
--------------------------------------------------------------------------------
-- freeradius apply handler
-- Author(s) [in order of work date]:
--       Fabián Omar Franzotti
--         
-- Configuration files referenced:
--    freeradius-proxy
--   
--
--------------------------------------------------------------------------------
print ("Committing Freeradius-proxy...")
os.execute("uci commit freeradius_proxy")
os.execute("rm /tmp/.uci/freeradius_proxy")
print ("Writing proxy.conf ...")
local freeradius = uciClass.new("freeradius")
if tonumber(freeradius.webadmin.userlevel) < 4 then
  -- Process proxy.conf
  local sep = ""
  local proxy = uciClass.new("freeradius_proxy")
  local proxy_str = "proxy server {\n"
  for i, v in pairs (proxy.server) do
    for k, val in pairs(v.values) do
      proxy_str = proxy_str .. k .."="..val.."\n"
    end
  end

  proxy_str = proxy_str .. "}\n\n"
  for i, v in pairs (proxy.realm) do
    proxy_str = proxy_str .. "realm "..v.values.community .." {\n"
    for k, val in pairs(v.values) do
      if k ~= "community" then
        if k == "nostrip" then
          proxy_str = proxy_str.."\t".."nostrip\n"
        else
          proxy_str = proxy_str .. "\t"..k.."="..val.."\n"
        end
      end
    end
    proxy_str = proxy_str .. "}\n\n"
  end
  local pepe = io.open("/etc/freeradius/proxy.conf","w")
  pepe:write(proxy_str)
  pepe:close()
end
__RESTART["radiusd"] = {}
__RESTART["radiusd"]["pkg"] = "freeradius"
__RESTART["radiusd"]["cfg"] = "webadmin"
__RESTART["radiusd"]["opt"] = "enable"
__RESTART["radiusd"]["init"] = "/etc/init.d/radiusd"
