#!/usr/bin/webif-page
<? 
. /usr/lib/webif/webif.sh
###################################################################
# freeloader-log.sh
# (c)2007 X-Wrt project (http://www.x-wrt.org)
# (c)2007-03-11 m4rc0
#
# version 1.2
#
# Description:
#	Shows the log file generated by freeloader.
#
# Author(s) [in order of work date]:
#	m4rc0 <janssenmaj@gmail.com>
#
# Major revisions:
#	
#
#
# NVRAM variables referenced:
#   none
#
# Configuration files referenced:
#   /etc/freeloader-include.sh
#
#

header_inject_head=$(cat <<EOF
<meta http-equiv="refresh" content="60;url=$SCRIPT_NAME" />

<script type="text/javascript">
<!--
function setDiv() {
	var viewarea = document.getElementById('viewarea'); 
	var windowheight = document.documentElement.clientHeight;
	viewarea.style.height = (windowheight - 344) + "px"; 
	viewarea.style.display = "block";
}

window.onload=setDiv
window.onresize=setDiv

// -->
</script>

EOF
)

header "Freeloader" "freeloader-log_subcategory#Log" "@TR<<freeloader-log_Freeloader_log#Freeloader log>>"
#Include settings
. /etc/freeloader-include.sh

#Check the required packages
is_package_installed "curl"
pkg_curl=$?
is_package_installed "ctorrent"
pkg_ctorrent=$?
is_package_installed "nzbget"
pkg_nzbget=$?

if [ $pkg_nzbget -eq "0" ] || [ $pkg_ctorrent -eq "0" ] || [ $pkg_curl -eq "0" ]; then
cat <<EOF
<div id="viewarea" style="overflow: scroll; width: 100%; display: none;">
<pre>
EOF
	if  [ -f "$LOG_DIRECTORY/freeloader.log" ]; then
		cat "$LOG_DIRECTORY/freeloader.log" | sed 's/&/\&amp;/; s/</\&lt;/; s/>/\&gt;/;'
	else
		echo "<p>@TR<<freeloader-log_No_entries_log#No entries in the log>></p>"
	fi
else
	echo "@TR<<freeloader-common_None_required_installed#None of the required packages is installed, check the upload-page to install the packages.>>"
fi
cat <<EOF
</pre>
</div>
EOF

footer ?>
<!--
##WEBIF:name:Freeloader:40:freeloader-log_subcategory#Log
-->
