#!/usr/bin/webif-page
<? 

###################################################################
# freeloader-log.sh
# (c)2007 X-Wrt project (http://www.x-wrt.org)
# (c)2007-03-11 m4rc0
#
#	version 1.2
#
# Description:
#	Shows the log file generated by freeloader.
#
# Author(s) [in order of work date]:
#	m4rc0 <janssenmaj@gmail.com>
#
# Major revisions:
#	
#
#
# NVRAM variables referenced:
#   none
#
# Configuration files referenced:
#   /etc/freeloader-include.sh
#
#

. /usr/lib/webif/webif.sh
header "Freeloader" "Freeloader log" "@TR<<Freeloader log>>" ' onresize="setDiv()" onload="setDiv()" '

#Include settings
. /etc/freeloader-include.sh

cat <<EOF
<script type="text/javascript">
<!--
//Set refresh timer for page (need to do this way, IE had problem with HTML refresh)
setTimeout("window.location='freeloader-log.sh';", 60000);

function setDiv()
{
var viewarea = document.getElementById("viewarea"); 
var windowheight = document.body.clientHeight;
viewarea.style.height = (windowheight - 344) + "px"; 
}
// -->
</script>
EOF

#Check the required packages
is_package_installed "curl"
pkg_curl=$?
is_package_installed "ctorrent"
pkg_ctorrent=$?
is_package_installed "nzbget"
pkg_nzbget=$?

#if one of the packages is installed the page can be displayed
if [ $pkg_nzbget -eq "0" ] || [ $pkg_ctorrent -eq "0" ] || [ $pkg_curl -eq "0" ]; then
cat <<EOF
<div ID="viewarea" style="overflow: auto; width: 100%;">
<pre>
EOF
	
	if  [ -f "$LOG_DIRECTORY/freeloader.log" ]; then
		cat "$LOG_DIRECTORY/freeloader.log" 
	else
		echo "No entries in the log"
	fi
	
cat <<EOF
</pre>
</div>
EOF
else
	echo "None of the required packages is installed, check the upload-page to install the packages."
fi

footer

?>
<!--
##WEBIF:name:Freeloader:40:Log
-->
