BEGIN TRANSACTION;
CREATE TABLE schema_info (version integer);
INSERT INTO "schema_info" VALUES(17);
CREATE TABLE boards ("id" INTEGER PRIMARY KEY NOT NULL, "name" varchar(255), "kernel" varchar(255), "description" varchar(255), "path" varchar(255));
INSERT INTO "boards" VALUES(1, 'brcm', '2.4', 'Broadcom BCM947XX', "ib_brcm-2.4");
CREATE TABLE filesystems ("id" INTEGER PRIMARY KEY NOT NULL, "name" varchar(255), "description" varchar(255), "overhead_size" integer, "compression_ratio" float);
INSERT INTO "filesystems" VALUES(1, 'squashfs', 'Highly compressed read-only root filesystem with an overlay filesystem. Changes will be written to a writable JFFS2 partition. (preferred filesystem type)', 315000, 0.5);
INSERT INTO "filesystems" VALUES(2, 'jffs2', 'JFFS2 root filesystem for flash. The complete root filesystem is writable.', 658280, 0.7);
INSERT INTO "filesystems" VALUES(3, 'ext2', 'EXT2 root filesystem.', 0, 1.0);
CREATE TABLE boards_filesystems ("board_id" integer, "filesystem_id" integer);
INSERT INTO "boards_filesystems" VALUES(1, 1);
INSERT INTO "boards_filesystems" VALUES(1, 2);
CREATE TABLE maintainers ("id" INTEGER PRIMARY KEY NOT NULL, "name" varchar(255), "email" varchar(255));
INSERT INTO "maintainers" VALUES(1, 'OpenWrt Developers Team', 'openwrt-devel@openwrt.org');
CREATE TABLE profiles ("id" INTEGER PRIMARY KEY NOT NULL, "board_id" INTEGER, "name" varchar(255));
INSERT INTO "profiles" VALUES(1, 1, "Test");
CREATE TABLE categories ("id" INTEGER PRIMARY KEY NOT NULL, "name" varchar(255), "description" varchar(255));
INSERT INTO "categories" VALUES(1, 'base', 'Essential packages, always needed');
CREATE TABLE dependencies ("dependant" integer, "depends_on" integer);
CREATE TABLE packages ("id" INTEGER PRIMARY KEY NOT NULL, "name" varchar(255), "description" varchar(255), "size" integer, "board_id" integer, "category_id" integer, "maintainer_id" integer, "version" varchar(255), "release" integer, "status" varchar(255));
INSERT INTO "packages" VALUES(1, 'kmod-broadcom-wl', 'wireless lan driver for broadcom devices', 248246, 1, 1, 1, '0.4', 1, 'active');
CREATE TABLE boards_packages("board_id" INTEGER, "package_id" INTEGER);
INSERT INTO "boards_packages" VALUES(1, 1);
CREATE TABLE profiles_packages ("profile_id" integer, "package_id" integer);
INSERT INTO "profiles_packages" VALUES(1, 1);
COMMIT;
