#!/bin/bash

echo "#Config file for L2TPns" > /etc/l2tpns/startup-config
echo "#Generated by X-WRT" >> /etc/l2tpns/startup-config

bindaddr=`uci get l2tpns.cfg1.ipaddr`
debug=`uci get l2tpns.cfg1.debug`
radport=`uci get l2tpns.cfg1.radport`
radacct=`uci get l2tpns.cfg1.radacct`
pidfile=`uci get l2tpns.cfg1.pidfile`
logfile=`uci get l2tpns.cfg1.logfile`
echo $bindaddr >> /etc/l2tpns/startup-config
echo $debug >> /etc/l2tpns/startup-config
echo $radport >> /etc/l2tpns/startup-config
echo $pidfile >> /etc/l2tpns/startup-config
echo $logfile >> /etc/l2tpns/startup-config
