__WIP = 1
__MENU.IW.OLSR = menuClass.new()
__MENU.IW.OLSR:Add("Core","olsr.sh")
__MENU.IW.OLSR:Add("General","olsr.sh?option=general")
--__MENU.IW.OLSR:Add("Ip Connect","olsr.sh?option=ipconnect")
__MENU.IW.OLSR:Add("Hna4","olsr.sh?option=hna4")
__MENU.IW.OLSR:Add("Hna6","olsr.sh?option=hna6")
__MENU.IW.OLSR:Add("Interfaces","olsr.sh?option=interfaces")
__MENU.IW.OLSR:Add("Status","olsr-status.sh")
__MENU.IW.OLSR:Add("Visualization","olsr-viz.sh")
