# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 17) do

  create_table "boards", :force => true do |t|
    t.column "name", :string
    t.column "arch", :string
    t.column "kernel", :string
    t.column "title", :string
    t.column "description", :text
    t.column "path", :string
  end

  create_table "boards_filesystems", :id => false, :force => true do |t|
    t.column "board_id", :integer
    t.column "filesystem_id", :integer
  end

  create_table "boards_packages", :id => false, :force => true do |t|
    t.column "board_id", :integer
    t.column "package_id", :integer
  end

  create_table "categories", :force => true do |t|
    t.column "name", :string
    t.column "description", :string
  end

  create_table "dependencies", :id => false, :force => true do |t|
    t.column "dependant", :integer
    t.column "depends_on", :integer
  end

  create_table "filesystems", :force => true do |t|
    t.column "name", :string
    t.column "description", :string
    t.column "overhead_size", :integer
    t.column "compression_ratio", :float
  end

  create_table "maintainers", :force => true do |t|
    t.column "name", :string
    t.column "email", :string
  end

  create_table "packages", :force => true do |t|
    t.column "name", :string
    t.column "title", :string
    t.column "description", :text
    t.column "size", :integer
    t.column "category_id", :integer
    t.column "maintainer_id", :integer
    t.column "version", :string
    t.column "status", :string
  end

  create_table "profiles", :force => true do |t|
    t.column "board_id", :integer
    t.column "name", :string
    t.column "title", :string
    t.column "description", :text
  end

  create_table "profiles_packages", :id => false, :force => true do |t|
    t.column "profile_id", :integer
    t.column "package_id", :integer
  end

end
