#!/bin/sh /etc/rc.common
START=50

BIN=olsrd
CONF_F=/var/etc/olsrd.conf
USE_CONF_F=/etc/olsrd.conf
DEFAULT=/etc/default/olsrd
RUN_D=/var/run
PID_F=$RUN_D/$BIN.pid


write_config_lua () {
  /usr/lib/webif/LUA/olsr/parsers
		USE_CONF_F="$CONF_F"
}
  
start() {
	$BIN -f "$USE_CONF_F" -nofork $OPTIONS &

	# write pid file (but strip out own pid ($$))
	mkdir -p $RUN_D
	PID=`pidof $BIN`
	echo ${PID%$$} > $PID_F
  /usr/lib/webif/LUA/cron_ctrl add "* * * * * /usr/lib/webif/LUA/olsr/minute.cron"
}

stop() {
  /usr/lib/webif/LUA/cron_ctrl del "* * * * * /usr/lib/webif/LUA/olsr/minute.cron"
	killall olsrd
}
