#!/usr/bin/lua
--------------------------------------------------------------------------------
-- freeradius apply handler
-- Author(s) [in order of work date]:
--       Fabián Omar Franzotti
--         
-- Configuration files referenced:
--    freeradius-check
--    freeradius-reply
--
--------------------------------------------------------------------------------
print ("Committing Freeradius-check...")
os.execute("uci commit freeradius-check")
print ("Committing Freeradius-reply...")
os.execute("uci commit freeradius-reply")

print ("Writing users...")
-- Process users
local user_str = ""
local sep = ""
local users_chk = uciClass.new("freeradius-check")
local users_rpl = uciClass.new("freeradius-reply")

for i=1, #users_chk.user do
  user_str = user_str.."\n\n"..users_chk.user[i].values.Username
  sep = "\t"
  for j, k in pairs (users_chk.user[i].values) do
    if j ~= "Username" then
      if string.trim(j) == "User_Password" then
        user_str = user_str..sep.. string.gsub(j,"_","-").." := \""..k.."\""
      else
        user_str = user_str..sep.. string.gsub(j,"_","-").." := "..k
      end
      sep = ", "
    end
  end
  sep = "\n\t"
  for j, k in pairs (users_rpl.user[i].values) do
    if j ~= "Username" then
      user_str = user_str..sep.. string.gsub(j,"_","-").." = "..k
      sep = ", "
    end
  end
end
sep = ""
user_str = user_str.."\n\nDEFAULT\t"
for i, v in pairs (users_chk.default) do
  if type(v) ~= "table" then
    user_str = user_str..sep..string.gsub(i,"_","-").." := "..v
    sep = ", "
  end
end
sep = "\n\t"
for i, v in pairs (users_rpl.default) do
  if type(v) ~= "table" then
    user_str = user_str..sep..string.gsub(i,"_","-").." = "..v
    sep = ",\n\t"
  end
end

local pepe = io.open("/etc/freeradius/users","w")
pepe:write(user_str)
pepe:close()
--dofile("/usr/lib/webif/LUA/freeradius-restart.lua")
__RESTART["radiusd"] = {}
__RESTART["radiusd"]["pkg"] = "freeradius"
__RESTART["radiusd"]["cfg"] = "webadmin"
__RESTART["radiusd"]["opt"] = "enable"
__RESTART["radiusd"]["init"] = "/etc/init.d/radiusd"
