#!/usr/bin/lua
--------------------------------------------------------------------------------
-- freeradius apply handler
-- Author(s) [in order of work date]:
--       Fabián Omar Franzotti
--         
-- Configuration files referenced:
--    freeradius-proxy
--   
--
--------------------------------------------------------------------------------
print ("Committing Freeradius-clients...")
os.execute("uci commit freeradius-clients")
print ("Writing clients.conf ...")
-- Process clients.conf
local sep = ""
local clients = uciClass.new("freeradius-clients")
local client_str = ""
for i=1, #clients.client do
  client_str = client_str .. "client "..clients.client[i].values.client.." {\n"
  sep = "\t"
  for k,v in pairs(clients.client[i].values) do
    if k ~= "client" then
      client_str = client_str..sep..k.."\t= "..v
      sep = "\n\t"
    end
  end
  client_str = client_str.."\n}\n"
end

local pepe = io.open("/etc/freeradius/clients.conf","w")
pepe:write(client_str)
pepe:close()
--dofile("/usr/lib/webif/LUA/freeradius-restart.lua")
__RESTART["radiusd"] = {}
__RESTART["radiusd"]["pkg"] = "freeradius"
__RESTART["radiusd"]["cfg"] = "webadmin"
__RESTART["radiusd"]["opt"] = "enable"
__RESTART["radiusd"]["init"] = "/etc/init.d/radiusd"
