#!/usr/bin/lua
--------------------------------------------------------------------------------
-- freeradius apply handler
-- Author(s) [in order of work date]:
--       Fabián Omar Franzotti
--         
-- Configuration files referenced:
--    freeradius-check
--    freeradius-reply
--
--------------------------------------------------------------------------------
dofile("/usr/lib/webif/apply/freeradius-check")