#!/bin/sh
# Copyright (C) 2006 OpenWrt.org
START=59

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/chilli
NAME=chilli
DESC=chilli
CONFFILE=/etc/chilli.conf
OPTS="--pidfile /var/run/$NAME.pid"

START_CHILLI=1

if [ -f /etc/chilli/default ] ; then
   . /etc/chilli/default
fi

if [ "$START_CHILLI" != "1" ] ; then
   echo "Chilli default off. Look at /etc/default/chilli"
   exit 0
fi

test -f $DAEMON || exit 0
test -f $CONFFILE || exit 0


. /etc/chilli/functions

check_required

RETVAL=0
prog="chilli"


case "$1" in
  start)
	echo -n "Starting $DESC: "
   /sbin/modprobe tun >/dev/null 2>&1
   echo 1 > /proc/sys/net/ipv4/ip_forward

   writeconfig
   radiusconfig

   (crontab -l 2>&- | grep -v $0
      test ${HS_ADMINTERVAL:-0} -gt 0 && echo "*/$HS_ADMINTERVAL * * * * $0 radconfig"
      echo "*/10 * * * * $0 checkrunning"
      #echo "*/2  * * * * $0 arping"
   ) | crontab - 2>&-

   ifconfig $HS_LANIF 0.0.0.0

  $DAEMON -- $OPTS
  RETVAL=$?
	echo "$NAME."
	;;
   
   checkrunning)
    local pid
		pid=$(cat "/var/run/$NAME.pid" 2>/dev/null)
		[ -n "$pid" -a -d "/proc/$pid" ] && {
			exit 0
		}
    $0 start
   ;;

   radconfig)
      [ -e $MAIN_CONF ] || writeconfig
      radiusconfig
   ;;

   restart)
      $0 stop
      $0 start
      RETVAL=$?
   ;;

  stop)
    local pid
		pid=$(cat "/var/run/$NAME.pid" 2>/dev/null)
		[ -n "$pid" -a -d "/proc/$pid" ] && {
      echo -n "Stopping $DESC: "
      crontab -l 2>&- | grep -v $0 | crontab -
      kill -TERM "$pid"
      [ "$?" -eq 0 ] && sleep 1
      [ ! -d "/proc/$pid" ] && echo "OK" || {
  			echo "Failed!"
        echo -n "Killing chillil..."
        kill -KILL "$pid"
        [ "$?" -eq 0 ] && echo "OK" || echo "Failed!"
      }
      exit 0
		}
		echo "$DESC was not running"
	;;

  reload)
    $0 restart
  ;;

  condrestart)
    local pid
		pid=$(cat "/var/run/$NAME.pid" 2>/dev/null)
		[ -n "$pid" -a -d "/proc/$pid" ] && {
      echo -n "Restarting $DESC: "
      $0 restart
      RETVAL=$?
		}
   ;;

   status)
		pid=$(cat "/var/run/$NAME.pid" 2>/dev/null)
		[ -n "$pid" -a -d "/proc/$pid" ] && {
      echo "$DESC running"
      exit 0
		}
    echo "$DESC stopped"
   ;;
   enable)
		echo "/etc/init.d/chilli start" > /etc/rc.d/S$START$NAME
		chmod 755 /etc/rc.d/S$START$NAME
    echo "$DESC enabled"
   ;;

   disable)
		rm /etc/rc.d/S$START$NAME 
    echo "$DESC disabled"
   ;;

  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|condrestart|status|reload|radconfig|enable|disable}" >&2
	exit 1
	;;
esac

exit 0
