#!/bin/sh /etc/rc.common
# Copyright (C) 2008 OpenWrt.org

START=44

EXTRA_COMMANDS="status active"
EXTRA_HELP="	status	Show current status
	active	Show Active connections"

start() {
	/lib/mroute/mroute start &
}

stop() {
	/lib/mroute/mroute stop
}

restart(){
	stop
	sleep 2
	start
}

status() {
	/lib/mroute/mroute status
}

active() {
	/lib/mroute/mroute active
}
